# .github/workflows/main.yaml
name: Main Workflow
on: 
  workflow_dispatch:
  push:

jobs:
  dsl-tests:
    concurrency:
      group: ${{ github.repository.name }}_dsl_tests-${{ github.head_ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
   

  

      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
