# .github/workflows/main.yaml
name: Main Workflow
on:
  workflow_dispatch:
    inputs:
      type:
        description: How the new release should be versioned
        required: true
        options:
          - "major"
          - "minor"
          - "patch"


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 
      uses: actions/setup-node@v1
      

      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
