# .github/workflows/main.yaml
name: Main Workflow
on: push

jobs:
  build:
    runs-on: ${{ matrix }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-10.15, windows-2019]
        include:
          - os: windows-2019
          - 32_bit: true
    steps:
      - name: Show env
        run: |
             set
             ls
             uname -a
       
      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
