# .github/workflows/main.yaml
name: Main Workflow
on: [push, repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Docs
      run: echo "test build docs"
    - name: Copy docs
      run: echo "copy docs" 
    - name: Commit files
      run: echo "commit files"
  

     
      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
