# .github/workflows/main.yaml
name: Main Workflow
on: 
 push:
  
jobs:
  release-pull-request-automation:
    if: ${{ github.event.ref_type == 'branch' && contains( github.ref, 'release/' ) }}
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    runs-on: ubuntu-latest
    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          if: ${{ always() }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create changeset for pull request
        run: |
          date > .release-artifact
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generating changeset for pull request"
          rm .release-artifact
          git commit -am "generating changeset for pull request"
          git push
      - name: Create Release Pull Request
        uses: woocommerce/automations@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          automations: release
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: ${{ always() }}
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
