# .github/workflows/main.yaml
name: Main Workflow
on: push

jobs:
  # Empty job if PR labeled with another label.
  stub:
    name: Empty job to prevent workflow fail
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.event.label.id != 2648778919
    steps:
      - name: stub action
        run: ": This job is used to prevent the workflow to fail when all other jobs are skipped."
      
       
      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
