# .github/workflows/main.yaml
name: Main Workflow
on: push

defaults:
  run:
    working-directory: nym-connect/desktop
    
jobs:
  markIssuesForTriage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1.0.0
    - name: Apply Issue Triage Label
      uses: actions/github@v1.0.0
      if: github.event.action == 'opened' && !contains(fromJSON('["bflad", "breathingdust", "ewbankkit", "gdavison", "maryelizbeth"]')), github.actor)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: label needs-triage


     
      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
