# .github/workflows/main.yaml
name: Main Workflow
on: 
  workflow_dispatch:
  push:

jobs:
  dsl-tests:
    concurrency:
      group: ${{ github.repository.name }}_dsl_tests-${{ github.head_ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: DSL tests
        uses: kiegroup/kie-ci/.ci/actions/dsl-tests@main
        with:
          main-config-file-repo: kiegroup/kogito-pipelines
          main-config-file-path: dsl/config/main.yaml
          branch-config-file-repo: kiegroup/kogito-pipelines

      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
