# .github/workflows/main.yaml
name: Main Workflow
on:
  push:
  
jobs:
  release_packages:
    name: Release Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        
      - name: Check that the generated files exist
        run: |
          set -e
          for file in ${{ join(matrix.generated-files.*, ' ') }}; do
            ls -lh $file
            test -f $file
          done
          
      - name: Possibly deploy WordPress plugin
        # Checks the changesets publishedPackages output
        # If there is a published package named "@faustwp/wordpress-plugin"
        # Then deploy the WordPress plugin
        # https://github.com/changesets/action#outputs
        if: contains(steps.changesets.outputs.publishedPackages.*.name, '@faustwp/wordpress-plugin')
        # Use a variant of 10up/action-wordpress-plugin-deploy that allows us to specify a PLUGIN_DIR
        # to support our monorepo structure.
        uses: ./.github/actions/release-plugin
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          PLUGIN_DIR: plugins/faustwp
          SLUG: faustwp

  

      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
