# .github/workflows/main.yaml
name: Main Workflow
on: 
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        # https://help.github.com/articles/virtual-environments-for-github-actions
        platform:
          - ubuntu-18.04
          - ubuntu-latest  # ubuntu-20.04
          - macos-latest  # macOS-10.15
          - windows-2016
          - windows-latest  # windows-2019
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9, '3.10', pypy-2.7, pypy-3.6, pypy-3.7]
        exclude:
          # https://github.com/actions/setup-python/issues/311
          - os: macos-latest
            python-version: pypy-3.6

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2

     
       

      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
