# .github/workflows/main.yaml
name: Main Workflow
on: 
  workflow_dispatch:
  push:

jobs:
  notify_if_not_dependabot:
    runs-on: ubuntu-latest
    steps:
    - name: Save GitHub Event to File
      run: echo ${{ github.event }} > event.json



  

      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
