# .github/workflows/main.yaml
name: Main Workflow
on: push

jobs:
  pr_deployment:
    # We only want to run the app if the PR Deployment label has been added
    if: ${{ github.event.label.id == 2500798832 }}

    name: Start server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
      
       
      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
