# .github/workflows/main.yaml
name: Main Workflow
on: 
 push:
  branches:
      - main
  tags:
      - +.+.+.+.+
 
jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
    
      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
