# .github/workflows/main.yaml
name: Main Workflow
on: push

jobs:
  push:
    name: Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Changed Files Exporter
        id: files
        uses: futuratrepadeira/changed-files@v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate changed file
        run: jq --raw-output "." "${{ steps.files.outputs.files_updated[0].file }}"
       
      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
