# .github/workflows/main.yaml
name: Main Workflow
on: 
   workflow_dispatch:
   push:
    
jobs:
  check_run:
    name: Start
    uses: "./.github/workflows/rel-lnx.yml"


    
      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
