# .github/workflows/main.yaml
name: Main Workflow
on:
  push:
  
jobs:
  build:
    name: build-and-test
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            go: "1.15"

          - os: ubuntu-latest
            go: "1.16"

          - os: ubuntu-latest
            go: "1.17"

          - os: ubuntu-latest
            go: &main-go-version "1.18"
            testWithMinio: true

          - os: ubuntu-latest
            go: "1.19"
            test: true

          - os: windows-latest
            go: *main-go-version
            testClientOnly: true
            noWebconsole: true

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/checkout@v3
     
  
  

      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
