# .github/workflows/main.yaml
name: Main Workflow
on: 
   workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from (make sure to use workflow from the same branch).'
        required: true
        type: choice
        options:
        - redhat-3.9
        - redhat-3.7
        - redhat-3.8
        - redhat-3.9
        - redhat-3.10
   push:
    
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        


    
      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
