# .github/workflows/main.yaml
name: Main Workflow
on: 
  workflow_dispatch:
  push:

jobs:
  test:
    name: Test on node and  with Postgres 
    runs-on: ubuntu-latest 
    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        # will assign a random free host port
        - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v2
     
      env:
        PGUSER: postgres
        PGPASSWORD: postgres
        PGDATABASE: postgres
        PGPORT: ${{ job.services.postgres.ports[5432] }}
   
      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
