# .github/workflows/main.yaml
name: Main Workflow
on: 
 push:
 
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions: read-all|write-all

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
          cache: 'yarn'

#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
