# .github/workflows/main.yaml
name: Main Workflow
on:
  push:
  
jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest

    steps:
    - uses: actions/checkout@v2
    - &checkout_submodules
      name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Test Bach Testing Framework
      run: ./run-tests.sh

  test-on-windows:
    name: Test on Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      <<: *checkout_submodules
    - name: Test Bach Testing Framework
      shell: bash
      run: bash ./run-tests.sh

      

      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
