# .github/workflows/main.yaml
name: Main Workflow
on:
  push:
  
jobs:
  release-test:
    # don't run on forks
    if: ${{ github.repository_owner == 'SmartThingsCommunity' }}

    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Package CLI
        id: package-cli
        # decouple Github Release from library-only publishing
        if: steps.changesets.outputs.published == 'true' && contains(steps.changesets.outputs.publishedPackages.*.name, '@smartthings/cli')
        run: | # output latest tag from changesets
          echo "::set-output name=tag::$(git describe --abbrev=0 --match '@smartthings/cli*')"
          npm run package

  

      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
