# .github/workflows/main.yaml
name: Main Workflow
on: 
 push:
  branches:
      - main
  tags:
      - +.+.+.+.+
 
jobs:
  dependabot:
    runs-on: ubuntu-latest
    
      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
