# .github/workflows/main.yaml
name: Main Workflow
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:
    branches: [ "main" ]
    
jobs:
  check_run:
    name: Start
    uses: "./.github/workflows/rel-lnx.yml"


    
      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
