# .github/workflows/main.yaml
name: Main Workflow
on: 
  workflow_dispatch:
  push:

jobs:
  notify_if_not_dependabot:
    if:  ${{ github.actor }} != 'dependabot'
    runs-on: ubuntu-latest
    steps:
    - name: Save GitHub Event to File
      run: echo ${{ github.event }} > event.json
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v5.0.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        raw-data: event.json


  

      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
