# .github/workflows/main.yaml
name: Main Workflow
on: 
 push:
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        version: 1.8
    - name: Build with Gradle
      run: ./gradlew build

      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
