# .github/workflows/main.yaml
name: Main Workflow
on:
  workflow_dispatch:
  push:
  

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matri
    - run: ${{ github.event.inputs.command }}
    env:
      GIT_COMMITTER_NAME: GitHub Actions
      GIT_AUTHOR_NAME: GitHub Actions
      EMAIL: github-actions[bot]@users.noreply.github.com



      

      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
