# .github/workflows/main.yaml
name: Main Workflow
on: push
    

jobs:
  package-build:
    name: Package Build
    needs: [ cmake-build ]
    # If any of the jobs listed in needs return "failure" then run this job
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    runs-on: ubuntu-latest
    container: ghcr.io/rpm-software-management/dnf-ci-host
    strategy:
      fail-fast: false  # don't fail all matrix jobs if one of them fails
      matrix:
        compiler: ['', clang]  # gcc is the default
    steps:
      - name: Check out ci-dnf-stack
        uses: actions/checkout@v2
     
      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
