# .github/workflows/main.yaml
name: Main Workflow
on: 
   workflow_dispatch:
   push:
    
jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: prebuilt step
    - run: sudo apt update
    - run: sudo apt install -y libgraphicsmagick1-dev libpng-dev libexiv2-dev libtiff-dev libjpeg-dev libxml2-dev libbz2-dev libfreetype6-dev libpstoedit-dev autoconf automake libtool intltool autopoint
   
    - uses: vapier/coverity-scan-action@v1
    - name: actual check
      with:
        email: ${{ secrets.COVERITY_SCAN_EMAIL }}
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}


    
      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
