# .github/workflows/main.yaml
name: Main Workflow
on: push

defaults:
  run:
    working-directory: nym-connect/desktop
    
jobs:
  publish-tauri:
    if: ${{ (startsWith(github.ref, 'refs/tags/nym-connect-') && github.event_name == 'release') || github.event_name == 'workflow_dispatch' }}
    strategy:
      fail-fast: false
      matrix:
        platform: [custom-runner-linux]
    runs-on: ${{ matrix.platform }}

    outputs:
      release_id: ${{ steps.create-release.outputs.id }}
      release_date: ${{ fromJSON(steps.create-release.outputs.assets[0].published_at) }}
      version: ${{ steps.release-info.outputs.version }}
      filename: ${{ steps.release-info.outputs.filename }}
      file_hash: ${{ steps.release-info.outputs.file_hash }}

    steps:
      - uses: actions/checkout@v2

      - name: Tauri dependencies
        run: >
          sudo apt-get update &&
          sudo apt-get install -y webkit2gtk-4.0 libayatana-appindicator3-dev
        continue-on-error: true

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
     
      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
