# .github/workflows/main.yaml
name: Main Workflow
on:
  workflow_run:
    types:
      - completed

jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_LOGIN: 'dependabot*'
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
       
      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
