# .github/workflows/main.yaml
name: Main Workflow
on:
  push:
  
jobs:
  update-snapshots:
    if: contains(needs.pull_request.outputs.labels.*.name, 'update snapshots')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      - name: Install browsers
        run: npx playwright install --with-deps
      - uses: actions/github-script@v3.1.0
        name: Download built storybook from CI
        id: storybook-artifact
       
    

      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
