# .github/workflows/main.yaml
name: Main Workflow
on:
  schedule:
    - '0 0 * * *'
  

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
   



      

      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
