# .github/workflows/main.yaml
name: Main Workflow
on: 
  workflow_dispatch:
  create:  # is used for publishing to PyPI and TestPyPI
    tags:  # any tag regardless of its name, no branches
  push:
jobs:
  bare_run:
    if: git tag -l --format='%(contents)' $(git describe --tags $(git rev-list --tags --max-count=1)) |grep -q "PHP 7.2 downgraded"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php_version: ['7.2', '7.3', '7.4', '8.0']
    steps:
      - uses: actions/checkout@v3



  

      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
