# .github/workflows/main.yaml
name: Main Workflow
on: 
  workflow_dispatch:
    inputs:
      source_branch:
        required: true
        default: 'Lede'
        type: choice
        options:
          - 'Lede'
          - 'Immortalwrt'
          - 'Official'
          - 'Xwrt'
          - 'Lede'
    
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        


    
      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
