# .github/workflows/main.yaml
name: Main Workflow
on: 
 push:
 
permissions: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
