# .github/workflows/main.yaml
name: Main Workflow
on:
  push:
  
jobs:
  on-success:
    name: Delete transient artifacts of successful workflow
    runs-on: ubuntu-latest
    permissions:
      # write permissions required for deleting artifacts
      actions: write
    # only run after successful jobs since some tests require retries
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Delete Artifacts
      run: |
        python .github/workflows/delete_artifacts.py \
          -t ${{ secrets.GITHUB_TOKEN }} \
          -a "transient_.*" \
          -r ${{ github.event.workflow_run.id }}

      env:
        GITHUB_REPOSITORY: ${{ vars.GITHUB_REPOSITORY }}

  

   



      

      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
