# .github/workflows/main.yaml
name: Main Workflow
on:
  push:
  
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - &checkout
        uses: actions/checkout@v2
      - &setup-go
        uses: actions/setup-go@v2
        with:
          stable: "false"
          go-version: "1.18.0-rc1"
      - run: make check
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - *checkout
      - *setup-go
      - run: make test

      

      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
