# .github/workflows/main.yaml
name: Main Workflow
on: 
 push:
 
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Create timestamp
      id: create_timestamp
      run: echo "::set-output name=timestamp::$(date '+%Y%m%d%H%M%S')"
      shell: sh
      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
