# .github/workflows/main.yaml
name: Main Workflow
on:
  push:
  
jobs:
  race-1: &run-race
    name: Race Test 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run race tests
        run: make race

  race-2:
    <<: *run-race
    name: Race Test 2

  

   



      

      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
