# .github/workflows/main.yaml
name: Main Workflow
on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: Git ref to run tests on
        required: true
        default: main
      test-type:
        description: Type of test to run
        options:
          - ci-stress
          - ci-nightly
        required: true
        type: string



jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 
      uses: actions/setup-node@v1
      

      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
