# .github/workflows/main.yaml
name: Main Workflow
on:
  
  workflow_dispatch:
    inputs:
      RELEASE:
        required: true
        type: string
      ARCH:
        required: true
        type: string
      IMAGE:
        required: true
        type: string
      DOCKERFILE:
        required: true
        type: string
      CACHE:
        required: false
        type: boolean
        default: true
      PUSH:
        required: false
        type: boolean
        default: true
      CACHE_SUFFIX:
        required: false
        type: boolean
        default: ""
  
jobs:
  main:
    name: Build APKs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
       

     
  
  

      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
