# .github/workflows/main.yaml
name: Main Workflow
on: push
    
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        id: stale
        with:
          stale-pr-message: 'This pull request has been open and inactive. It will be closed shortly.'
          days-before-stale: 7
          days-before-close: 0
          exempt-draft-pr: true
          exempt-pr-labels: 'Pending: Work in Progress,WIP'
      - name: Print outputs
        run: echo ${{ join(steps.stale.outputs.*, ',') }}
     
      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
