# .github/workflows/main.yaml
name: Main Workflow
on:
  workflow_dispatch:
  push:
  

jobs:
  # This job is used to determine what files have changed and is used by later jobs to determine if they should run.
  setup:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      frontend: ${{ steps.check-frontend.outputs.any_changed }}
      markdown: ${{ steps.check-markdown.outputs.any_changed }}
      json: ${{ steps.check-json.outputs.any_changed }}
      python: ${{ steps.check-python.outputs.any_changed }}
      workflows: ${{ steps.check-workflows.outputs.any_changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
    
    
  # Repository wide checks

  codeql:
    name: CodeQL
    uses: ./.github/workflows/codeql.yml

      

      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
