# .github/workflows/main.yaml
name: Main Workflow
on:
  push:
    types:
      - tags
  workflow_dispatch:

jobs:
  job:
    name: release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            triplet: x64-linux
           
    steps:
      - uses: actions/checkout@v1
      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
