# .github/workflows/main.yaml
name: Main Workflow
on:
  push:
  
jobs:
  test:
    name: Build APKs
    runs-on: ubuntu-latest
    # Skip for `main` and the merge queue if the branch is up to date with `develop`
    if: github.ref != 'refs/heads/main' && github.event.merge_group.base_ref != 'refs/heads/develop'
    strategy:
      matrix:
        variant: [debug, release, nightly, samples]
      fail-fast: false
    # Allow all jobs on develop. Just one per PR.
    concurrency:
      group: ${{ github.ref == 'refs/heads/develop' && format('build-develop-{1}', github.sha) || format('build-{0}-{1}', matrix.variant, github.ref)  }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
        
      - name: Use JDK 17
        uses: actions/setup-java@v3
      
     
  
  

      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
