# .github/workflows/main.yaml
name: Main Workflow
on:
  push:
  
jobs:
  provide-runner:
    name: Start self-hosted YC runner
    timeout-minutes: 5
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-yc-runner.outputs.label }}
      instance-id: ${{ steps.start-yc-runner.outputs.instance-id }}
    steps:
      - name: Start YC runner
        id: start-yc-runner
        uses: yc-actions/yc-github-runner@v1

  main:
    uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
    needs:
      - provide-runner

    with:
      runner_kind: self-hosted
      log_suffix: ya-x86-64${{ inputs.sanitizer != 'none' && format('-{1}', inputs.sanitizer) }}
    secrets: inherit


     
  
  

      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
