# .github/workflows/main.yaml
name: Main Workflow
on:
  push:
  
jobs:

  test-on-windows:
    name: Test on Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
    - name: Test Bach Testing Framework
      shell: bash
      run: bash ./run-tests.sh

      

      
#   build:
#     uses: ehsansiddiqui/ml-platform/.github/workflows/test-wf.yml@main
