name: Test instance deployment

on:
  push:
  workflow_call:
    inputs:
      needs_zebra_state:
        type: boolean
        default: false
env: {}
  
jobs:
  test-without-cached-state:
    runs-on: ubuntu-latest
    steps:
      - name: Inject slug/short variables
        run: printenv
