name: Test instance deployment

on:
  workflow_dispatch:
    inputs: 
      version: 
        type: text
        description: 'Version number Eg: 4.2.0' 
jobs:
  test-without-cached-state:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
          os: [ubuntu, windows, macos]
          python-version: ['3.8', '3.9', '3.10', '3.11', 'pypy-3.8', 'pypy-3.9']
          exclude:
            - os: windows
              python-version: pypy33
    steps:
      - name: Inject slug/short variables
        run: printenv
