name: Test instance deployment

on:
  workflow_dispatch:
    inputs: 
      version: 
        type: text
        description: 'Version number Eg: 4.2.0' 
jobs:
  test-without-cached-state:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
        django-version: ['2.2', '3.1', '3.2', '4.0rc1', 'main']

        exclude:
          - python-version: '3.6'
            django-version: 'main'
          - python-version: '3.7'
            django-version: 'main'
          - python-version: '3.10'
            django-version: '2.2'
          - python-version: '3.10'
            django-version: '3.1'
          - python-version: '3.6'
            django-version: '4.0b1'
          - python-version: '3.7'
            django-version: '4.0b1'
    steps:
      - name: Inject slug/short variables
        run: printenv
