name: Test instance deployment

on:
  workflow_dispatch:
    inputs: 
      version: 
        type: text
        description: 'Version number Eg: 4.2.0' 
jobs:
  test-without-cached-state:
    runs-on: ubuntu-latest
    steps:
      - name: Inject slug/short variables
        run: printenv
